# Generated by Django 5.2.7 on 2025-12-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practica',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
